on:
  push:
    tags:
      - "v*"
name: Publish to Factorio mod portal
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish overhead-electrification
      uses: Penguin-Spy/factorio-mod-portal-publish@main
      with:
        factorio-api-key: ${{ secrets.FACTORIO_MOD_API_KEY }}
